# Server Name
spring:
  application.name: booking-service
  datasource:
    url: jdbc:mysql://localhost:3306/full_stack
    username: root
    password: root1
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: validate
        '[format_sql]': true
        dialect: org.hibernate.dialect.MySQLDialect
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        
# Enable Actuator
management.endpoints.web.exposure.include: "*"

# Server Port
server:
  port: 8000 

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#Logger
logging.level:
  web: DEBUG
  '[com.microservices.bookingservice]': DEBUG