# Server Name
spring:
  application:
    name: admin-service

# Admin Server Port
server:
  port: 7700
  
# Enable Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Eureka Server URL to Resister Service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#Logger
logging.level:
  debug: DEBUG
  '[com.microservices.adminservice]': DEBUG
  # Can be DEBUG for Development
  # Can be ERROR after Development
  # Can be OFF to turn the logger statemts off