spring:
  application:
    name: price-service
  datasource:
    url: jdbc:mysql://localhost:3306/java_projects
    username: root
    password: root1

server:
  port: 8001  # Choose a unique port

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
