spring:
  application:
    name: gateway-service

server:
  port: 8000  # Choose a unique port

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#Logger
logging.level:
  debug: DEBUG
  '[com.microservices.priceservice]': DEBUG
  # Can be DEBUG for Development
  # Can be ERROR after Development
  # Can be OFF to turn the logger statemts off