spring:
  application:
    name: gateway-service  # Defines the name of the application as it will appear in Eureka and other places.

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enables automatic route discovery from Eureka.
          lowerCaseServiceId: true  # Converts the service IDs to lower case when discovering routes.

management.endpoints.web.exposure.include: "*"

server:
  port: 8765  # Specifies the port on which the Gateway Service will run.

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # URL of the Eureka server for service registration and discovery.

logging:
  level:
    web: DEBUG
    '[com.microservices.gatewayservice]': DEBUG  # Sets the logging level specifically for the Price Service proxy to DEBUG.
    # The logging level can be adjusted based on the development stage (DEBUG, ERROR, OFF).